#! /bin/bash
#
# FILES -- bash ファイルリスト
#
source ${funcs_dir}/exists.bash
source ${funcs_dir}/if.bash
source ${funcs_dir}/log.bash
source ${funcs_dir}/require.bash

require       \
    __        \
    array     \
    debug     \
    date      \
    defun     \
    required  \
    file      \
    misc      \
#
